// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyuI4_IZZ5z1Et1WQ2_7Ya_VkfrxscVpc',
    appId: '1:519112775023:web:d60fd991097ff32b23c49a',
    messagingSenderId: '519112775023',
    projectId: 'sahalat-609df',
    authDomain: 'sahalat-609df.firebaseapp.com',
    storageBucket: 'sahalat-609df.firebasestorage.app',
    measurementId: 'G-YE08GNYMGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrPH8BJnVnabQK1pFmy5MJmSJotZpciyU',
    appId: '1:519112775023:android:30862f92eb20818c23c49a',
    messagingSenderId: '519112775023',
    projectId: 'sahalat-609df',
    storageBucket: 'sahalat-609df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRY8mXA3Zhf60fhMk8LHIkEZCCtCkKygY',
    appId: '1:519112775023:ios:d443402216ac72d523c49a',
    messagingSenderId: '519112775023',
    projectId: 'sahalat-609df',
    storageBucket: 'sahalat-609df.firebasestorage.app',
    iosBundleId: 'com.example.sahalat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRY8mXA3Zhf60fhMk8LHIkEZCCtCkKygY',
    appId: '1:519112775023:ios:d443402216ac72d523c49a',
    messagingSenderId: '519112775023',
    projectId: 'sahalat-609df',
    storageBucket: 'sahalat-609df.firebasestorage.app',
    iosBundleId: 'com.example.sahalat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyuI4_IZZ5z1Et1WQ2_7Ya_VkfrxscVpc',
    appId: '1:519112775023:web:5a733e3a7aa6883f23c49a',
    messagingSenderId: '519112775023',
    projectId: 'sahalat-609df',
    authDomain: 'sahalat-609df.firebaseapp.com',
    storageBucket: 'sahalat-609df.firebasestorage.app',
    measurementId: 'G-LZT94CG53G',
  );
}
